In [15]:
!pip install numpy

In [6]:
import numpy as np
data = np.array([1,2,3,4,5])
print(data, len(data), type(data), data.shape)

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr[0])
print(arr[0][0])

arr2 = np.array([1,2,3,4,5,6,7,8,9])
print(arr2[1:5])

arr3 = np.array([5,22,65,6,1,654,77])
print(np.sort(arr3))

arr4 = np.array(['kind', 'smart', 'fruit', 'apple'])
print(np.sort(arr4))

arr5 = np.array([3,2,14,9,10,12])
print(np.where(arr5 == 9))

arr6 = np.array([9,5,8])
arr7 = np.array([55,89,76])
combined_array = np.concatenate((arr6, arr7))
print(combined_array)

[1 2 3 4 5] 5 <class 'numpy.ndarray'> (5,)
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
1
[2 3 4 5]
[  1   5   6  22  65  77 654]
['apple' 'fruit' 'kind' 'smart']
(array([3]),)
[ 9  5  8 55 89 76]
